CREATE OR REPLACE VIEW planet_osm_line AS
SELECT osm_id
-- original columns
, layer    as "layer"
, tags     as "tags"
, way      as "way"
, way_area as "way_area"
, z_order  as "z_order"
-- calculated columns
, osml10n_get_placename_from_tags(tags,true,false,' - ','de',way)   as "localized_name_second"
, osml10n_get_placename_from_tags(tags,false,false,' - ','de',way)  as "localized_name_first"
, osml10n_get_name_without_brackets_from_tags(tags,'de',way)        as "localized_name_without_brackets"
, osml10n_get_streetname_from_tags(tags,true,false,' - ','de', way) as "localized_streetname"
, COALESCE(tags->'name:hsb',tags->'name:dsb',tags->'name')          as "name_hrb"
, osm_tag2num(tags->'width')                                        as "num_width"
-- hstore tag 'columns' (sorted)
, tags->'CEMT' AS "CEMT"
, tags->'abandoned' AS "abandoned"
, tags->'access' as "access"
, tags->'addr:interpolation' as "addr:interpolation"
, tags->'admin_level' AS "admin_level"
, tags->'aerialway' as "aerialway"
, tags->'aeroway' as "aeroway"
, tags->'attraction' AS "attraction"
, tags->'barrier' as "barrier"
, tags->'bicycle' as "bicycle"
, tags->'boundary' AS "boundary"
, tags->'bridge' as "bridge"
, tags->'building' as "building"
, tags->'construction' as "construction"
, tags->'covered' as "covered"
, tags->'culvert' as "culvert"
, tags->'direction' AS "direction"
, tags->'disused' as "disused"
, tags->'embankment' as "embankment"
, tags->'fenced' AS "fenced"
, tags->'foot' as "foot"
, tags->'highway' as "highway"
, tags->'historic' as "historic"
, tags->'horse' as "horse"
, tags->'int_name' as "int_name"
, tags->'intermittent' as "intermittent"
, tags->'junction' as "junction"
, tags->'landuse' AS "landuse"
, tags->'lanes' AS "lanes"
, tags->'leisure' as leisure
, tags->'living_street' AS "living_street"
, tags->'lock' as "lock"
, tags->'man_made' as "man_made"
, tags->'motorboat' AS "motorboat"
, tags->'motorcar' as "motorcar"
, tags->'name' as "name"
, tags->'name:de' as "name:de"
, tags->'name:en' as "name:en"
, tags->'natural' as "natural"
, tags->'oneway' as "oneway"
, tags->'operator' as "operator"
, tags->'power' as "power"
, tags->'proposed' as "proposed"
, tags->'railway' as "railway"
, tags->'razed' AS "razed"
, tags->'ref' as "ref"
, tags->'route' as "route"
, tags->'sac_scale' AS "sac_scale"
, tags->'service' as "service"
, tags->'sport' AS "sport"
, tags->'station' AS "station"
, tags->'surface' as "surface"
, tags->'toll' AS "toll"
, tags->'tracktype' as "tracktype"
, tags->'trail_visibility' AS "trail_visibility"
, tags->'tunnel' as "tunnel"
, tags->'usage' AS "usage"
, tags->'via_ferrata_scale' AS "via_ferrata_scale"
, tags->'voltage' AS "voltage"
, tags->'waterway' as "waterway"
, tags->'width' as "width"
-- after initial import add further columns below this line only
FROM planet_osm_hstore_line;

GRANT select ON planet_osm_line to public;
