CREATE OR REPLACE VIEW planet_osm_point AS
SELECT osm_id
-- original columns 
, layer as   "layer"
, tags as    "tags"
, way as     "way"
, z_order as "z_order"
-- calculated columns
, osml10n_get_placename_from_tags(tags,true,false,chr(10),'de',way) as localized_name_second
, osml10n_get_placename_from_tags(tags,false,false,chr(10),'de',way) as localized_name_first
, osml10n_get_name_without_brackets_from_tags(tags,'de',way) as localized_name_without_brackets
, osml10n_get_streetname_from_tags(tags,true,false,chr(10),'de', way) as localized_streetname
, COALESCE(tags->'name:hsb',tags->'name:dsb',tags->'name') as name_hrb
, osm_tag2num(tags->'ele') as "num_ele"
, osm_tag2num(tags->'width') as "num_width"
-- hstore tag 'columns' (sorted)
, tags->'abandoned' AS "abandoned"
, tags->'access' as "access"
, tags->'addr:housename' as "addr:housename"
, tags->'addr:housenumber' as "addr:housenumber"
, tags->'admin_level' as "admin_level"
, tags->'aerialway' as "aerialway"
, tags->'aeroway' as "aeroway"
, tags->'amenity' as "amenity"
, tags->'barrier' as "barrier"
, tags->'bicycle' AS "bicycle"
, tags->'boundary' as "boundary"
, tags->'building' as "building"
, tags->'bus' AS "bus"
, tags->'capital' as "capital"
, tags->'castle_type' AS "castle_type"
, tags->'communication:radio' AS "communication:radio"
, tags->'communication:television' AS "communication:television"
, tags->'covered' AS "covered"
, tags->'craft' as "craft"
, tags->'denomination' as "denomination"
, tags->'denotation' AS "denotation"
, tags->'direction' as "direction"
, tags->'disused' as "disused"
, tags->'ele' as "ele"
, tags->'ford' as "ford"
, tags->'generator:source' as "generator:source"
, tags->'harbour' AS "harbour"
, tags->'height' AS "height"
, tags->'highway' as "highway"
, tags->'historic' as "historic"
, tags->'iata' as "iata"
, tags->'industrial' as "industrial"
, tags->'int_name' as "int_name"
, tags->'junction' as "junction"
, tags->'landuse' as "landuse"
, tags->'leaf_type' AS "leaf_type"
, tags->'leisure' as "leisure"
, tags->'lock' as "lock"
, tags->'man_made' as "man_made"
, tags->'memorial:type' AS "memorial:type"
, tags->'military' as "military"
, tags->'name' as "name"
, tags->'name:de' as "name:de"
, tags->'name:en' as "name:en"
, tags->'natural' as "natural"
, tags->'office' AS "office"
, tags->'operator' as "operator"
, tags->'otm_isolation' as "otm_isolation"
, tags->'place' as "place"
, tags->'population' as "population"
, tags->'power' as "power"
, tags->'power_source' as "power_source"
, tags->'public_transport' as "public_transport"
, tags->'railway' as "railway"
, tags->'ref' as "ref"
, tags->'religion' as "religion"
, tags->'ruins' as "ruins"
, tags->'service' as "service"
, tags->'shop' as "shop"
, tags->'site_type' AS "site_type"
, tags->'sport' as "sport"
, tags->'station' as "station"
, tags->'subway' as "subway"
, tags->'summit:cross' AS "summit:cross"
, tags->'tourism' as "tourism"
, tags->'tower:type' AS "tower:type"
, tags->'train' AS "train"
, tags->'waterway' as "waterway"
, tags->'wetland' as "wetland"
-- after initial import add further columns below this line only
FROM planet_osm_hstore_point;

GRANT select ON planet_osm_point TO public;
